credentials:
  usernames:
    mahesh:
      email: mahesh@gmail.com
      name: Mahesh BS
      password: $2b$12$froXPssvPd.BsC5/oHwYs.ZWsXJMZCvUQZyRCB.YWSCtaKjQo9bUq                  # To be replaced with hashed password
    kumar:
      email: kumar@gmail.com
      name: Amith Kumar
      password: def              # To be replaced with hashed password
    teja:
      email: teja@gmail.com
      name: Teja kumar
      password: teja123
    kavya:
      email: kavya@gmail.com
      name: kavya
      password: $2b$12$uztmwbLuvZSAiZ7V3/HhCu1auVpVr/R1LubSeROyO6mT1m.xFj0Tm

cookie:
  expiry_days: 30
  key: "my_app"              # Must be string
  name: "login_app"
preauthorized:
  emails:
  - mahesh@gmail.com